### ISSUE TITLE
[BUG] There is no compat between Raised and Create, so this is causing issues.

### ISSUE THREAD

**Issue by murao-kun** [yurisuika/Raised#19]
Create recently added trains and speed bar is replacing xp bar, like it is on animals that you ride.
Seems like with Raised installed it is acting not like it should be. Making it both speed bar and xp bar visible at the same time in different UI high levels.
Screenshot: 
![image](https://user-images.githubusercontent.com/110398598/185759062-fed9e61b-00f9-45c8-bfb5-cee9a64567a6.png)
Create is not out officialy on 1.19 yet, but I managed to compile it and still test. (So that mean the issue is actual for both 1.18 and 1.19)

**Comment by yurisuika** [comment]
It would seem that they have simply placed this bar over the XP bar instead of replacing it. That would most certainly cause issues with texture packs. As you say it is an early version so maybe it is just a quick way of getting it there for testing.
It would be recommended that they look into resolving it on their end by hooking into where the XP bar is placed while also rendering the XP bar non-visible. Not only could it be done in a way that does not require mod compatibility, but also in a way that would not affect texture packs.

**Comment by murao-kun** [comment]
This is also an issue on 1.18 version too, there the mod is officially released. They are not disabling xp bars, this is not even needed. But the issue is that it is not rising to match Raised adjustments.

**Comment by yurisuika** [comment]
Support has been added for trains and toolboxes! Hopefully this is all that conflicts, as I am unfamiliar with Create.

**Comment by murao-kun** [comment]
Thank you!

**Comment by yurisuika** [comment]
I have been informed that there is another aspect, the backtank/diving helmet timer that should be changed as well. That will be in next update. Hopefully that covers it all.
