### ISSUE TITLE
Mixin crash with latest version of create

### ISSUE THREAD

**Issue by newtrogicNexus** [yurisuika/Raised#29]
After a bit of testing, I singled down the mod causing the issue to be this one. Crash log provided:
[crash-2023-02-07_22.32.44-fml.txt](https://github.com/yurisuika/Raised/files/10682535/crash-2023-02-07_22.32.44-fml.txt)

**Comment by yurisuika** [comment]
Thanks! I look into this soon. It is possible I may have last tested this on "e" for 1.18.2.

**Comment by yurisuika** [comment]
Okay, I see what is wrong. When I revamped the Forge version to use Yarn mappings + Loom, I had just copied over the mixins from the Fabric version to save time. However, unlike the 1.16.5 version of Create (and the Fabric Port), the 1.18.2+ versions had to have the mixin done differently.

So, long story short, I blew it. Didn't test the 1.18.2 Forge version with Create. I can't test the 1.19.2 versions unless I backport version 1.2.0, but it should work the same as the 1.18.2 version anyways according to the code.

I'll have this fixed in the next release! Basically just gotta revert to what it was before with different mappings.
