### ISSUE TITLE
FML reports server as incompatible when Raised is installed on client

### ISSUE THREAD

**Issue by davidfrp** [yurisuika/Raised#32]
![billede](https://user-images.githubusercontent.com/6499570/219873584-40324f60-5a32-4f91-a6ca-6b0b63d3ad30.png)

I then tried to add Raised to the server, though this prevented the server entirely from even being able to start, as Raised is client-only.

**Comment by yurisuika** [comment]
Would you please specify versions and provide relevant logs?

**Comment by yurisuika** [comment]
My guess right now is it probably has something to do with commands on the Forge build, cause I could not find enough information on how to create client commands on Forge.

**Comment by yurisuika** [comment]
Ah, I misunderstood, I think. You're saying it is reporting it as incompatible, but nothing is actually preventing you from joining, yes?

You should be able to run this fine with no problems, except on 1.17 and 1.16, because as far as I could tell there is no way to make client commands on Forge in those versions, and they do not support them anymore.

While I haven't ran a Forge server since 1.16, I somewhat recall that red X showing up in the past, so perhaps it simply means there are mods running on the client that are not on the server and is normal?

If you can provide an example of a client side mod that does not do this, please share, and perhaps I may learn how to give it the green.

**Comment by davidfrp** [comment]
I can still join, yes. It's merely a slight hiccup for those downloading a modpack, who might think something went wrong.

Pretty much any other client side mods that I have, doesn't mark the server as incompatible, even though it's only on the client and not the server. Here's some of them.
* chat_heads-0.9.0-forge-1.19.2
* ClearDespawn-forge-1.19.2-1.1.10
* EquipmentCompare-1.19.2-forge-1.3.2
* Fallingleaves-1.19.1-1.3.1
* farsight-1.19.2-2.1
* MouseTweaks-forge-mc1.19-2.23
* waveycapes-forge-1.3.2-mc1.19.2

Maybe the mod needs to marked as a client mod somewhere? I'm not quite into the developing of Minecraft mods so can't say with certainty.

**Comment by yurisuika** [comment]
Well it is marked for CLIENT already in the mods.toml for both MC and Forge. The ordering is set to AFTER for Forge, although that does not seem to make a difference for the checkmark. Even my Dyed mod does this and that is extremely simple because it is basically just a mixin (hell the Fabric version _is_ just the mixin).

As for right now I am at a loss as to why this might be happening; I am not seeing anything in some of those other mods that might indicate where the issue lies.

**Comment by davidfrp** [comment]
It might be worth looking at https://docs.minecraftforge.net/en/latest/concepts/sides/#writing-one-sided-mods
Not sure how the mod is implemented currently. So can't tell whether this is already the case. Would've tried working it in myself, had the code been available.

Though I hope it might help.

**Comment by yurisuika** [comment]
Ah interesting, well I checked ClearDespawn and MouseTweaks, but neither had `displayTest`. FallingLeaves did but they put it at the top so I never noticed it. But anyways that does the trick!

![image](https://user-images.githubusercontent.com/7410303/225206339-f488580b-57a8-48e6-8ba6-b0de7a085811.png)

I've added GitHub Actions to the project so there should be a build up on here once the changes are pushed. Thanks!
