### ISSUE TITLE
Documentation for mod devs and question reguarding a change

### ISSUE THREAD

**Issue by Minenash** [yurisuika/Raised#37]
While after looking at the code (or other mod's code) I could find the object share key, it would be nice if there was a wiki page that described it.

Also, while splitting up chat/hud into two variables definitely seems useful, was there a reason `raised:distance` wasn't kept for compatibility with mods that were using it?

**Comment by yurisuika** [comment]
Done! https://github.com/yurisuika/Raised/wiki/Using-ObjectShare

I was trying to promote the person's mod who suggested adding it, but yes that is probably important to document.

As far as that goes, I attempted to do every breaking thing at once for one update to be once and done. I was aware of only two mods that used to and contacted both directly, and only one other came up after as having broken, so it wasn't too bad. I didn't keep that object because of OCD.

**Comment by Minenash** [comment]
> I didn't keep that object because of OCD.
Lol. I have two checks now just in case someone is using an older raised version :P

But cool, thanks for the docs!

**Comment by Minenash** [comment]
Though, maybe the page should be called "Adding compatibility"? Tbh, I didn't even know object share was a thing until I added raised support

**Comment by yurisuika** [comment]
I'll just append it to the Compatibility page then and remove that one.
