### ISSUE TITLE
Pls. Update to Forge versions > 47.1.13

### ISSUE THREAD

**Issue by Tursiops-G** [yurisuika/Raised#45]
Breaks under Forge versions 47.1.14 and up (1.20.1).

**Comment by yurisuika** [comment]
I will when it becomes the new recommended version. Currently 47.1.0 is, and it is compatible.

**Comment by yurisuika** [comment]
What we have here is they have actually patched the tooltip's method to replace the entire body to a reference of a new method which they have created that is mostly the same as the original but with an additional parameter.

While this was the one mixin method in the GUI class still using `ModifyVariable` and not `ModifyArg`, it isn't just broken because it is no longer looking for ordinal "2", even a more unsavory `Redirect` would still have broken because nothing exists there now except that one line. Rather, that mixin as well as the one for the music disk overlay have to be removed or altered.

Thus, there is no way to make this backwards compatible with ANY version before 47.1.14.

You will find a compatible build in the Actions tab when this is fixed, but this is very much a snapshot thing and I won't make a general release for it until it gets put in a Recommended version.

**Comment by yurisuika** [comment]
the mod is being rewritten and should support the full gamut now
