### ISSUE TITLE
items in hotbar not correct

### ISSUE THREAD

**Issue by lalamapaka** [yurisuika/Raised#5]
# The items in the hot bar aren't shown correctly see picture
![image](https://user-images.githubusercontent.com/75388592/161423017-e55312a9-ab91-4284-90fd-8252b1d76678.png)

Version of the mod is 1.0.5

mods:
[see here](https://github.com/lalamapaka/Faster-than-light#mods)

These are the warns i found in the logs
[12:11:05] [main/WARN]: Error loading class: squeek/appleskin/client/HUDOverlayHandler (java.lang.ClassNotFoundException: squeek/appleskin/client/HUDOverlayHandler)
[12:11:05] [main/WARN]: @Mixin target squeek.appleskin.client.HUDOverlayHandler was not found raised.mixins.json:mods.appleskin.HUDOverlayHandlerMixin
[12:11:05] [main/WARN]: Error loading class: me/lizardofoz/inventorio/client/ui/HotbarHUDRenderer (java.lang.ClassNotFoundException: me/lizardofoz/inventorio/client/ui/HotbarHUDRenderer)
[12:11:05] [main/WARN]: @Mixin target me.lizardofoz.inventorio.client.ui.HotbarHUDRenderer was not found raised.mixins.json:mods.inventorio.HotbarHUDRendererMixin

**Comment by yurisuika** [comment]
The Fabric version, yes? It is likely a mod conflict. Does it work fine when installed by itself? If so, let me know what mod is conflicting and I can add support for it.

Those warnings can be ignored, they are just letting you know the support for Appleskin and Inventorio cannot be applied because those mods are not present.

**Comment by lalamapaka** [comment]
Yes it's the fabric version alone it works it's the mod: Controller Support Mod, can't find it on curseforge since it's down

**Comment by yurisuika** [comment]
Changing the priority of the mixin to -1 resolved it, making it change the value after the other mod. CSM just redirects to the same method, so it basically overwrites what Raised does there. They probably shouldn't be using a Redirect for what they are accomplishing, as it could have been achieved in other ways without breaking compatibility. This might inadvertently make Raised conflict with other mods, but we will see what comes. If that happens I'll have to revert the change.

**Comment by lalamapaka** [comment]
Should I report the issue in they're github?

**Comment by yurisuika** [comment]
Do what you want. I can't imagine a whole lot of mods out there are messing with this specific method call, but who knows.

As far as possible conflicts with changing the priority for it to happen afterwards, if something redirects the methods (like CSM does) but to a different method instead of just the same one, then when Raised would try to modify the value it could crash or make undesired results. I probably wouldn't worry about this happening, though, as I can't imagine much actually changes these to their own methods. Something that does would probably be a major UI overhaul.

Having it at a high priority, it would do it first, thus getting ahead of anything else that wants to change it and thus it wouldn't be able to crash. Of course CSM redirected it afterwards and thus the change never came to be, but it didn't crash or anything like that.
