### ISSUE TITLE
[BUG] Add-on files cannot be installed separately on Modrinth app

### ISSUE THREAD

**Issue by BrandonItaly** [yurisuika/Raised#56]
The Raised mod on Modrinth does not have the addons as separate projects which makes it so that the addons cannot be installed through the Modrinth app. When trying to install any of the addon files, only the primary file is able to be installed.

https://github.com/modrinth/theseus/issues/712

**Comment by yurisuika** [comment]
This is really down to Modrinth's site functionality. I've already talked with them about it and they do not plan to support downloading their own additional files section despite displaying it to the user.

**Comment by yurisuika** [comment]
I understand this, but this in itself is not an issue with Raised, this is an issue with Modrinth. They copied Curseforge but didn't give additional files their own IDs. I think they're doing a great thing with Modrinth, but its a flaw to not follow the precedent set by CF and is going to shake stuff up, as seen here. But I get it, its not the best solution if people rely on launchers to install mods. I've never done that in my life, so its not a contingency I was prepared for or even knew was a thing.

Regardless, I have for about 3 weeks been making attempts at rewriting the mod to have a broad compatibility, so it will work a bit differently and not have any specific mod support, internal as before or internal as now. Some mods that I could not support before will now be able to move, some that I had to inject into will not, and this varies by mod launcher and game version. It's really down to being so many ways to register HUD elements. Forge changes MC code and encapsulates the different HUD elements so mods can reference them for where they want their HUD elements to be in context, so the way mods register their HUD stuff on it will work more naturally. Fabric is a bit more wild west, so its hit and miss.

But I am ending the way of mod support through injecting code into other mods as before because its problematic on a number of levels. Raised will still have its way for mods to support it on Fabric as before, that is not changing. But in some cases like Arrows Info or Farmer's Delight on Fabric, they had added support for Raised, but now work without needing that. As such, this will be able to be disabled so they don't have to release a new version, otherwise their stuff would be doubled in offset. It will be a problem though if you have mods that don't work without using that support and have ones that still have that support but no longer need it.

You will still be able to run those additional files with the new version of the mod. Some mods like Botania for Fabric and Create Fabric on some versions will not work in the new way because of how they register their stuff, so in these cases that may be required.

But, if you are like most people who are mainly interested in Appleskin support, fear not because that is one mod that works flawlessly on every version and on both Forge and Fabric.
