### ISSUE TITLE
Please add Axiom compatibility

### ISSUE THREAD

**Issue by thesh1xx** [yurisuika/Raised#60]

**Comment by yurisuika** [comment]
Is this with version 3.0.0?

I tried the mod and could not find anything relevant, so if you could be more specific because I am entirely unfamiliar with the mod.

**Comment by yurisuika** [comment]
I looked around and found another mod also called Axiom, this one might be the one you are talking about?
https://modrinth.com/mod/axiom

If so, enabling Extended mod support will raise its ALT menu.

But I think this ticket might have been from before 3.x had been officially released, so that wasn't a thing back then.
