### ISSUE TITLE
3.0.0 Crash when joining a server

### ISSUE THREAD

**Issue by Hlebuw3k** [yurisuika/Raised#63]
Quilt 1.20.1, downgrading to 2.0.0 fixes the crash. Log file at line 11460
[2023-10-10-7.log](https://github.com/yurisuika/Raised/files/12858420/2023-10-10-7.log)

**Comment by yurisuika** [comment]
Remove Raised x Appleskin, as it will not work with Raised 3.x. Also, it is no longer needed, Appleskin works natively now.

**Comment by Hlebuw3k** [comment]
Great mod and everything but this is the second time where I had issues with it after updating to a big x.0.0 release and didnt have any issues before that.

**Comment by yurisuika** [comment]
But look at it this way, the reason it is crashing is because those methods were moved (along with the rest of the config stuff) into its own separate class. If I didn't do that, you'd be reporting instead that the Appleskin stuff was raised twice as high!

Either way, you'd have to delete the Appleskin support mod to fix your issue, you'd just have a different issue.

**Comment by Hlebuw3k** [comment]
> Well that is why it is a major version increment!

That's why it should be a beta release, to test for the bugs first.

**Comment by yurisuika** [comment]
It is not a bug, you're just trying to combine incompatible versions. When 3.x came out there was a big large red disclaimer appended to the repo sites that the 2.x modular system was not compatible with 3.x. But since it has been long since then and few people used the modular system in the first place, those disclaimers are gone.

**Comment by Hlebuw3k** [comment]
And how was I supposed to see the disclaimer as a regular user, updating the mod from a previous version with a mod loader like multi-mc, where it barely even shows the mod page? Same goes for the modular system, how was I supposed to know that I need to install more things without launching the game, seeing that the mod is broken, going through all my mods and seeing that an update requires additional downloads from me? I have not had issues since then, but 2 major mod updates that break the mod is not how it should have been. I can only hope it does not break randomly again when I decide to update my mods before playing the game again.

**Comment by yurisuika** [comment]
Well I have only uploaded the mod to GitHub, Curseforge, and Modrinth. If you use 3rd party software/websites, then you're going to have to deal with the caveats that those bring. I did drop the modular system because Modrinth did not want to support the installation of additional files on their own launcher. While pretty much being a clone of Curseforge, one feature they did lack was having individual identifiers for the additional files uploaded, thus the system could not work with any launcher that used Modrinth.

As for the modular system, when you went to the download page for a release on Curseforge or Modrinth, all of the additional files were right there with the main file. Combine that with the rather short description of the mod, it wasn't too hard to grasp if you took 30 seconds to read. If you just use shortcut links to get downloads, you're missing out on all of that and changelogs. Changelogs are pretty vital in understanding why something may no longer be functional. If you didn't read the changelog or the description, then you lost out on gaining the information that would have solved your inquiry.

Once again, major version changes are totally fair to denote lack of backwards compatibility. Not everyone versions their software in accordance to such good practice, but I did, and so it is really on you for updating from 1.x -> 2.x and 2.x -> 3.x and expecting that nothing might have changed. Maybe you don't know the significance of that, but in the future you should understand what that entails.
