### ISSUE TITLE
Sometimes items are raised

### ISSUE THREAD

**Issue by Aceplante2** [yurisuika/Raised#69]
Sometimes items are raised a few pixels causing them to misalign with the inventory grid. But this only happens in survival.

forge 1.18.2

**Comment by yurisuika** [comment]
If you are having some issue, provide more information like logs, mod list, screenshots, whatever you can.

**Comment by Aceplante2** [comment]
Yes, at the time I had removed your mod temporarily and it hasn't happened since, but Ill test it out later.

**Comment by mikewk** [comment]
I've run into this issue as well in 1.18.2.  In my case have narrowed it down to an interaction with Mantle's extra heart rendering feature.  With the feature turned on, it looks like somethings are rendered correctly (Hotbar, Hearts, Inventory items), some things aren't being moved at all (Armor, Hunger, Xp) and some things are being moved too low (Inventory background, Game menus).  I'm guessing this is because the Hotbar and Inventory items are rendered before the Hearts, the Armor/Hunger/Xp are translated by your mod (so they're erroneously moved down but then back up), and the rest of the UI is just moved down.

As a note, all of this testing has been done on a fresh 1.18.2 with only Raised, Mantle, and Tinker's Construct.

I haven't really dug deep into the MC gui code, but looking at the Mantle code (https://github.com/SlimeKnights/Mantle/blob/1.18.2/src/main/java/slimeknights/mantle/client/ExtraHeartRenderHandler.java) and your code my best guess is that Mantle is cancelling the PreLayer event, which your code catches and translates the GUI back.  Then Mantle sends a PostLayer event, which you also catch and translates the gui some more causing everything rendered after this point to be too low.

I don't really know enough about how the GUI renderer is supposed to work to say what needs to be fixed.  As in I don't know if Mantle is breaking some type of contract by cancelling the PreLayer event then sending a PostLayer event, or if that's a valid case that you should be catching, likely by keeping track of whether or not you've translated the GUI back already in the PostLayer event.

I've attached some screenshots.  The first are at 5 pixels, the last one is at 50 pixels to really highlight the elements that are being moved down.

![2023-11-11_14 21 20](https://github.com/yurisuika/Raised/assets/6451356/cf290870-0194-497f-9cb9-898bfbec5172)
![2023-11-11_14 21 26](https://github.com/yurisuika/Raised/assets/6451356/76cdaa36-4427-4904-94c9-700fcc9ed3fb)
![2023-11-11_14 21 45](https://github.com/yurisuika/Raised/assets/6451356/38cc4a5b-a78c-4fda-be85-b32cef842142)
![2023-11-11_14 33 22](https://github.com/yurisuika/Raised/assets/6451356/8d2a590f-92e2-4b0b-ad5a-b040595f8799)

**Comment by Aceplante2** [comment]
sure enough i am using mantle

**Comment by yurisuika** [comment]
Nicely done, it seems to work just fine.

Interestingly enough, nothing seemed to be amiss until I uninstalled Health Overlay, which does the same exact thing. So I guess between the two one disables the other or itself.
