### ISSUE TITLE
3.1.0 No longer works for servers with custom resource packs

### ISSUE THREAD

**Issue by Commander07** [yurisuika/Raised#77]
3.1.0 Made it so the selector must now be located in the mod namespace which means servers would have to add compatibility to support Raised. Perhaps an option to opt-out of this behavior could be added so the mod continues to work on servers like Wynncraft.

With Raised:
![image](https://github.com/yurisuika/Raised/assets/45269106/457e30d1-0876-41b4-85a2-4cd1db486f74)

Without Raised:
![image](https://github.com/yurisuika/Raised/assets/45269106/8caedb56-28fb-4950-8a4a-71d0d193833a)

**Comment by yurisuika** [comment]
The primary point of the mod is to fix the selector, though, so it seems rather antithetical to add such an option. Mojang just broke it even worse in 1.20.2 by breaking up the GUI texture atlas and cropped the selector texture to 23 pixels in height. This solution was deemed the best option because it left full control of how the fixed selector would look in the user's hands, which would allow for it having the exact appearance of how the selector would have appeared prior to 1.20.2.

The server you are playing on should have downloaded their pack to the `server-resource-packs` folder. You can take that asset and make your own pack to add the fixed texture. If you were playing on the server in a previous version of the game, you might have a pack from it with the old atlas from which you could get the full 24x24 selector texture from, but in your case it would appear that there may be white-space at the bottom, which would mean you could just expand the texture canvas by 1 pixel downward and it should have the same result.
