### ISSUE TITLE
Custom Hotbar Selector texture not being used

### ISSUE THREAD

**Issue by Obscure2020** [yurisuika/Raised#80]
I use the resource pack [VanillaXBR](https://modrinth.com/resourcepack/vanillaxbr), as well as a Fabric mod stack that includes Raised. Just today, I noticed that Raised is not actually using the `hotbar_selection.png` texture provided by the resource pack.

I am using Raised v3.1.0.

With Raised:

![2023-12-27_15 12 47](https://github.com/yurisuika/Raised/assets/69320464/6793f696-11be-47f9-a268-c0c7c783f4c9)

Without Raised:

![2023-12-27_15 20 18](https://github.com/yurisuika/Raised/assets/69320464/3924b705-ec1c-4009-be52-4bf7f591d7c9)

Is this a Raised bug, or do we need to specify the texture in a different form / with a different name / in a different place in the resource pack to make Raised use it?

**Comment by Obscure2020** [comment]
And if we _do_ need to specify the texture in a different place, what is the exact path within the resource pack where we should add the texture? This specific information should be publicly documented, but it does not appear to be listed in the GitHub Readme, the Modrinth Readme, or the GitHub Wiki.

**Comment by yurisuika** [comment]
This is only for 1.20.2+ because Mojang butchered the selector further when they split up the atlas and cut off the selector now in texture not just code. While they did match the selector's code to render 23px in height as for what is shown on the vanilla Java screen (before it was cut off at 22px from a total of 24px), the new split GUI sprites use their own method that stretches the entire texture; this forces Raised to have to have a new asset that is not cut off in texture because such a whole texture no longer exists in the vanilla assets.

You'll find the same asset under the the same directory just under the `raised` namespace that should be a 24px tall (at vanilla scaling) image instead of a 23px tall one. You will need to provide your own fixed asset for 1.20.2+ for the selector.

**Comment by Obscure2020** [comment]
So the path is `assets/raised/textures/gui/sprites/hud/hotbar_selection.png`.

Thanks for the info.\
Cheers!
